# Generated by Django 5.2.16 on 2026-07-21 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_space'),
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SPACE_CREATED', 'Space Created'), ('DOCUMENT_ADDED', 'Document Added'), ('DOCUMENT_UPDATED', 'Document Updated'), ('DOCUMENT_DELETED', 'Document Deleted'), ('MEMBER_JOINED', 'Member Joined'), ('MEMBER_REMOVED', 'Member Removed')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='spaces.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
