# Generated by Django 6.0.6 on 2026-07-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
    ]
