# Generated by Django 6.0.6 on 2026-07-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
