# Generated by Django 5.2.16 on 2026-07-21 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documentversion_options_and_more'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='spaces.space'),
        ),
    ]
