# Generated by Django 5.2.16 on 2026-07-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
